-- Secondo fattore di autenticazione (TOTP), opzionale per utente.
--
-- Da quando l'app risponde sul dominio pubblico, il form di login è raggiungibile da
-- chiunque e fra un estraneo e i dati dei clienti c'è solo una password: il limitatore per
-- IP ferma la forza bruta, non la password già nota per phishing o riuso.
--
-- `totp_confirmed_at` è il vero interruttore: la 2FA è attiva solo se valorizzato. Un
-- segreto generato e mai confermato (QR mostrato e finestra chiusa) resta lì innocuo e
-- viene sovrascritto al tentativo successivo, senza bisogno di ripulirlo.
--
-- `totp_last_step` ricorda l'ultimo passo temporale accettato: un codice vale trenta
-- secondi, e senza questa memoria chi lo intercetta potrebbe rigiocarlo finché è vivo.
ALTER TABLE "user" ADD COLUMN "totp_secret" varchar(255);--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "totp_confirmed_at" timestamp;--> statement-breakpoint
ALTER TABLE "user" ADD COLUMN "totp_last_step" integer;--> statement-breakpoint
-- Codici di recupero: senza una via d'uscita la 2FA sarebbe soprattutto un nuovo modo di
-- restare chiusi fuori. In tabella solo lo sha256, come per i token di sessione: sono già
-- casuali, quindi non c'è nulla da indovinare a forza bruta e un archivio di backup non
-- deve consegnare codici riutilizzabili.
CREATE TABLE "user_recovery_code" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_recovery_code_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"code_hash" varchar(64) NOT NULL,
	"used_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user_recovery_code" ADD CONSTRAINT "user_recovery_code_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- Unico indice, e fa due lavori: la ricerca del codice presentato al login (che parte
-- sempre dall'utente già identificato dalla password) e il divieto di due codici uguali
-- nello stesso blocco, che darebbe all'utente sette possibilità invece di otto.
CREATE UNIQUE INDEX IF NOT EXISTS "user_recovery_code_user_id_code_hash_idx" ON "user_recovery_code" USING btree ("user_id","code_hash");
